# Misclassification rate for k=2 with optimal label alignment via LSAP
# THis was generated by LLM and I should probably go back to my previous
# Version
mis_rate_aligned_k2 <- function(g, pred) {
  # ensure clue is available
  if (!requireNamespace("clue", quietly = TRUE)) stop("Need package 'clue'")
  C <- as.matrix(table(g, pred))
  M <- max(C)
  assignment <- clue::solve_LSAP(M - C)  # permutation of predicted labels
  map_pred_to_true <- rep(NA_integer_, 2)
  map_pred_to_true[assignment] <- 1:2
  pred_aligned <- map_pred_to_true[pred]
  mean(pred_aligned != g)
}



#save_result(meta = mis_rate_aligned_k2)